[[server]]
# listen するホスト名 or IP
# default: 0.0.0.0
host = "localhost"
# listen するポート番号
# default: 80
port = 8080

# サーバー名 (optional)
server_name = ["example.com", "www.example.com"]

# エラーページ (optional)
error_page = { 404 = "/404.html" }

# body のサイズ上限
# default: 1048576 (1MiB)
client_max_body_size = 1048576

# ルート設定
[[server.location]]
# マッチするパス (REQUIRED)
path = "/"
# 許可するメソッド
# default: GET
allowed_methods = ["GET", "POST"]
# ルートディレクトリ (REQUIRED)
root = "/var/www/html"
# index ファイル
# default: index.html
index = "index.htm"
# directory listing
# default: off
autoindex = "on"

# location は複数定義できる
[[server.location]]
path = "/redirect"
# リダイレクト先 (optional)
# redirect があったら、他の location の設定を無視する
redirect = "https://example.com"

# 最低限の location の設定
[[server.location]]
path = "/files"
root = "/var/www/files"

# server は複数定義できる
[[server]]
host = "localhost"
port = 8082

[[server.location]]
path = "/"
root = "/var/www/test"
index = ["index.php"]