#!/bin/bash

# HTTP Header
echo "Content-Type: text/html"
sleep 10
echo ""

# HTML Content
echo "<html>"
echo "<head><title>CGI Test</title></head>"
echo "<body>"
echo "<h1>Hello, CGI!</h1>"
echo "<p>This page was generated by a Shell script.</p>"
echo "</body>"
echo "</html>"