[[server]]
host = 'localhost'
port = 8080
[server.error_page]
404 = "example/html/error/404.html"

[[server.location]]
path = '/'
root = 'example/html'

[[server.location]]
path = '/other'
root = 'example/html'
index = 'home.html'

[[server.location]]
path = '/'
root = 'example/uploads'
allowed_methods = ['POST']

[[server.location]]
path = '/cgi'
root = 'example'
allowed_methods = ['GET', 'POST']
cgi_extensions = ['.cgi', 'py']

# --

[[server]]
port = 8081
server_name = ['upload.example.com']

# upload したファイルの取得
[[server.location]]
path = '/'
root = 'example/uploads'
autoindex = 'on'

# --

[[server]]
port = 8082
server_name = ['redirect.example.com']

# NOTE: /foo/bar はどこにリダイレクトするべきか?
[[server.location]]
path = '/'
redirect = 'http://localhost:8080'
