[[server]]
host = 'localhost'
port = 8080

[[server.location]]
path = '/'
root = 'example/html'

[[server.location]]
path = '/other'
root = 'example/html/other'
index = 'top.html'

# upload したファイルの取得
[[server.location]]
path = '/files'
root = 'example/html/uploads'
autoindex = 'on'

# --

[[server]]
port = 8080
server_name = ['upload.example.com']

# upload 専用
[[server.location]]
path = '/'
root = 'example/html/uploads'
allowed_methods = ['POST']

# --

[[server]]
port = 8081
server_name = ['redirect.example.com']

# NOTE: /foo/bar はどこにリダイレクトするべきか?
[[server.location]]
path = '/'
redirect = 'http://localhost:8080'
