name: ctest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ctest:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.28.0"
          ninjaVersion: "^1.11.1"

      - uses: hendrikmuhs/ccache-action@v1.2.11
        with:
          key: ${{ matrix.os }}
          create-symlink: true

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -j

      - working-directory: build
        run: ctest -j
